version: "2"

linters:
  default: standard
  enable:
    - misspell
    - revive

  settings:
    revive:
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: warning

  exclusions:
    paths:
      - mocks

formatters:
  enable:
    - gofmt
    - goimports

  exclusions:
    paths:
      - mocks
